app/urls.py
from django.urls import path
from .views import (
    ProductsListView, ProductDetailView, create_product, ProductCreate, ProductUpdate, ProductDelete,
    subscriptions
)

urlpatterns = [
    path('', ProductsListView.as_view(), name='product_list'),
    path('<int:pk>/', ProductDetailView.as_view(), name='product_detail'),
    path('create/', create_product, name='product_create'),
    path('createbygen/', ProductCreate.as_view(), name='product_create_by_generic'),
    path('<int:pk>/update/', ProductUpdate.as_view(), name='product_update'),
    path('<int:pk>/delete/', ProductDelete.as_view(), name='product_delete'),
    path('subscriptions/', subscriptions, name='subscriptions'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('accounts/', include('django.contrib.auth.urls')),
    # path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),  # авторизация только по allauth
    path('products/', include('app.urls')),
]

app/models.py
from django.contrib.auth.models import User
from django.core.cache import cache
from django.db import models
from django.core.validators import MinValueValidator
from django.urls import reverse


# Категория, к которой будет привязываться товар
class Category(models.Model):
    # названия категорий тоже не должны повторяться
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name.title()


class Material(models.Model):
    # наименование материала
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name.title()


# Товар для нашей витрины
class Product(models.Model):
    name = models.CharField(max_length=50, unique=True)  # названия товаров не должны повторяться
    description = models.TextField()
    quantity = models.IntegerField(validators=[MinValueValidator(0)])
    # поле категории будет ссылаться на модель категории
    category = models.ForeignKey(to='Category', on_delete=models.CASCADE, related_name='products')  # все продукты в категории будут доступны через поле products
    price = models.FloatField(validators=[MinValueValidator(0.0)])
    materials = models.ManyToManyField(Material, through='ProductMaterial')

    # допишем свойство, которое будет отображать есть ли товар на складе
    @property
    def on_stock(self):
        return self.quantity > 0

    def __str__(self):
        return f'{self.name.title()}: {self.description[:20]}'

    def get_absolute_url(self):
        return reverse('product_detail', args=[str(self.id)])  # Указывает куда редиректиться после додбавления новой записи

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs) # сначала вызываем метод родителя, чтобы объект сохранился
        cache.delete(f'product-{self.pk}') # затем удаляем его из кэша, чтобы сбросить его

class ProductMaterial(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    material = models.ForeignKey(Material, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.product.name} | {self.material.name}'


class Subscription(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.CASCADE, related_name='subscriptions',)
    category = models.ForeignKey(to=Category, on_delete=models.CASCADE, related_name='subscriptions',)

app/templates/product.html
<!--  наследуемся от шаблона default.html, который мы создавали для flatpages -->
{% extends 'default.html' %}

<!-- Название у нас будет product -->
{% block title %}
Product
{% endblock title %}

<!-- В контенте на странице мы выводим сам товар, идентификатор которого был передан в url -->
{% block content %}
<h1>{{ product }}</h1>
{% endblock content %}

app/templates/product_delete.html
{% extends 'default.html' %}

{% block content %}
<h1>Удаление товара</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем "{{ object.name }}?</p>
    <input type="submit" value="Delete"/>
</form>
{% endblock content %}

app/templates/product_edit.html
{% extends 'default.html' %}

{% block content %}
<h1>Товар</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save"/>
</form>
{% endblock content %}

app/templates/products.html
<!--  наследуемся от шаблона default.html, который мы создавали для flatpages -->
{% extends 'default.html' %}

{% load custom_filters %} <!-- Подключаем новый файл с нашим фильтром -->
{% load custom_tags %} <!-- Подключаем новый файл с нашим тегом -->

<!-- Название у нас будет products -->
{% block title %}
Products
{% endblock title %}

<!-- В контенте на странице мы выводим все товары -->
{% block content %}
<h1>Все товары</h1>
<!-- Используя переданную из вьюхи переменную time_now а применив к ней фильтр (я б назвал форматом) date.
По назначению он очень похож на метод strftime у объекта datetime в Python - вывод времени в указанном формате-->
<!-- Вот так выглядело использование переменной и фильтра -->
<!-- <h3>{{ time_now|date:'M d Y' }}</h3> -->
<!-- А вот так мы используем наш тег-->
<h3>{% current_time '%b %d %Y' %}</h3>

<!-- если в переменной next_sale будет None, то выводится указанный в фильтре текст -->
<h3>{{ next_sale|default_if_none:"Чуть позже сообщим о распродаже!" }}</h3>
<hr>
{# Добавляем форму, которая объединяет набор полей, которые будут отправляться в запросе #}
<form action="" method="get">
   {# Переменная, которую мы передали через контекст, может сгенерировать нам форму с полями #}
   {{ filterset.form.as_p }}
   {# Добавим кнопку отправки данных формы #}
   <input type="submit" value="Найти" />
</form>
<hr>

{# теперь будем проверять наличие прав, чтобы отобразить ссылку #}
    {% if perms.app.add_product %}
    <a href="{% url 'product_create' %}">Добавить товар</a>
{% endif %}


{% if products %}
    <table>
        <tr>
            <th>Название</th>
            <th>Описание</th>
            <th>Категория</th>
            <th>Цена</th>
            <th>количество</th>
            {# Условие получается составным. #}
            {% if perms.app.change_product or perms.app.delete_product %}
            <td>Действия</td>
            {% endif %}
        </tr>
        {% for product in products %}
        <tr>
            <td>{{ product.name|truncatewords:4 }}</td> <!--спецаильный фильтр truncatewords ограничивает вывод текста до указанного числа слов-->
            <td>{{ product.description|truncatechars:15 }}</td> <!--truncatechars ограничивает вывод до указанного числа символов-->
            <td>{{ product.category.name }}</td>
            <td>{{ product.price|currency:"rub" }}</td>
            <td>{{ product.quantity }}</td>

            <td>
                {# А здесь доступ для каждой ссылки теперь будем проверять отдельно #}
                {% if perms.app.change_product %}
                <a href="{% url 'product_update' pk=product.id %}">Изменить</a>
                {% endif %}
                {% if perms.app.delete_product %}
                <a href="{% url 'product_delete' product.id %}">Удалить</a>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </table>
{% else %}
    <h2>Товаров нет!</h2>
{% endif %}

{# Добавляем пагинацию на страницу #}
{# информация о предыдущих страницах #}
{% if page_obj.has_previous %}
    <a href="?{% url_replace page=1 %}">1</a>
    {% if page_obj.previous_page_number != 1 %}
        ...
        <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
    {% endif %}
{% endif %}

{# информация о текущей странице #}
{{ page_obj.number }}

{# информация о следующих страницах #}
{% if page_obj.has_next %}
    <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
    {% if page_obj.paginator.num_pages != page_obj.next_page_number %}
        ...
        <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
    {% endif %}
{% endif %}

{% endblock content %}

app/templates/subscriptions.html
{% extends 'default.html' %}

{% block title %}
Subscriptions
{% endblock title %}

{% block content %}
    {% for category in categories  %}
        <p>
            {{ category.name }}
            <form method="post">
                {% csrf_token %}
                <input type="hidden" name="category_id" value="{{ category.id }}" />

                {% if category.user_subscribed %}
                    <button disabled>Подписаться</button>
                    <button name="action" value="unsubscribe">Отписаться</button>
                {% else %}
                    <button name="action" value="subscribe">Подписаться</button>
                    <button disabled>Отписаться</button>
                {% endif %}
            </form>
        </p>
    {% endfor %}
{% endblock content %}